name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy repo to Raspberry Pi and run deploy script
        env:
          RPI_HOST: ${{ secrets.RPI_HOST }}
          RPI_PATH: ${{ secrets.RPI_PATH }}
          RPI_BRANCH: ${{ github.ref_name }}
          RPI_SERVICE: ${{ secrets.RPI_SERVICE }}
        run: |
          # push is not required here because GitHub already has the code; we will trigger a git pull on the Pi
          ssh -o StrictHostKeyChecking=no "$RPI_HOST" "cd $RPI_PATH && git fetch --all --prune && git reset --hard origin/$RPI_BRANCH && if [ -f requirements.txt ]; then if [ ! -d .venv ]; then python3 -m venv .venv; fi; . .venv/bin/activate; pip install -r requirements.txt; fi && if [ -n \"$RPI_SERVICE\" ]; then sudo systemctl restart $RPI_SERVICE; fi"
